nome = input("Informe o nome: ")
idade = input("Informe a idade: ")
ano_nasc = input("Informe o ano de nascimento: ")
print(nome)
print(idade)
print(ano_nasc)
calculo = 2030 - int(ano_nasc)
print(calculo)